### ISSUE TITLE
i am insterested in this circuit plugin development

### ISSUE THREAD

**Issue by ghost** [Wang-Yue/Circuit#1]
it would be nice to see something like this with ability to receive more that one note per step as well as make it have 8 instances out with tabs (and ability to mute outputs individually) - each instance going to a different midi channel as well as applying all of the scales and root note settings like an actual circuit.  and make it black background. 
Also ability to select pad colors.

**Comment by Wang-Yue** [comment]
Hi, @modman2019 welcome!

If you want to contribute a feature available in the official novation Circuit, feel free to send PRs for review. Once the code looks good, I will merge your changes to this project.
